language: node_js 
node_js:
- 12.22.7

cache: npm

install:
- npm install


branches:
  only:
  - master

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api_key: 9eab1ffd-8bac-45fd-8b90-23965847f3ab
  app: no-de-travis





