language: node_js 
node_js:
- 12.22.7

cache: npm

install:
- npm install

# script:
# - npm run test:unit 
# - npm run build

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   local_dir: dist
#   on:
#     branch: master


