language: node_js 
node_js:
- 12.22.7

cache: npm

install:
- npm install

script:
- npm run test

branches:
  only:
  - master

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api_key: 9eab1ffd-8bac-45fd-8b90-23965847f3ab
  app: no-de-travis





